### ISSUE TITLE
Referer Restrictions question

### ISSUE THREAD

**Issue by SRandazzo** [mcabs3/google-places-web#10]
👋Hi and thanks for this library!

I have a general question about referer restrictions on API keys.

For our web project, we have the referer restriction enabled to prevent leaking + unauthorized use of the key. 

Thus, when i try to use the same key in ReactNative, I get back:
`"API keys with referer restrictions cannot be used with this API."`

This got me wondering if it is safe to use the key with this module in our RN app?

I know that the native iOS implementation of google-places does a similar type of "referral restriction" by reading and matching the bundle-id of the app (always unique)

Any thoughts on this?

Thanks again!

**Comment by mcabs3** [comment]
Hi there,
Sorry for seeing your question so late in the game. This library is a wrapper around the node based library of Google Places. because of this, it doesn't have the capabilities to access/read native integrations like the native sdk would be able to do. So I would agree with you that if you are looking to use the referer restrictions to integrate with the native SDK.

From my experience with RN, I have not found an issue with my apps having the key properly placed in my app. I have a build process that handles securing my key, and then a process when the app launches to store the encrypted key into redux that I can pull and use, but that is just one idea for you.
